booking_website_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('diary/', include('diary.urls'), name='diary-urls'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls'), name='home-urls'),
]

diary/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.my_details, name='diary'),
    path('<slug:slug>/edit_booking/<int:booking_id>', views.booking_edit, name='booking_edit'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.MovieList.as_view(), name='home'),
    path('<slug:slug>/', views.movie_detail, name="movie_detail"),
    path('diary/', include('diary.urls')),
]

diary/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Movie

DAY = ((0, "Monday"), (1, "Tuesday"), (2, "Wednesday"), (3, "Thursday"), (4, "Friday"))

# Create your models here.
class Detail(models.Model):
    this_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="details")
    first_name = models.CharField(max_length=200, default="FirstName")
    last_name = models.CharField(max_length=200, default="LastName")
    updated_on = models.DateTimeField(auto_now=True)

class Booking(models.Model):
    which_movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="bookings")
    which_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="booker")
    which_day = models.IntegerField(max_length=200, choices=DAY, default=0)
    created_on = models.DateTimeField(auto_now=True)

home/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = ((0, "Free-Space"), (1, "Fully-Booked"))

# Create your models here.
class Movie(models.Model):
    movie_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, null="tempSlug")
    listing_author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="movie_title"
    )
    movie_year = models.TextField(max_length=200, null="tempYear")
    movie_desc = models.TextField()
    movie_image = models.TextField(max_length=200, null="tempImg1")
    movie_image_desc = models.TextField(max_length=200, null="tempImgDesc")
    meal_name = models.CharField(max_length=200, unique=True)
    listed_on = models.DateTimeField(auto_now_add=True)
    available = models.IntegerField(choices=STATUS, default=0)

diary/views.py
from django.shortcuts import render, get_object_or_404,reverse
from django.contrib.auth.models import User
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Detail
from .models import Booking
from home.book_form import UserBooking
from home.models import Movie

# Create your views here.
def my_details(request):
    """
    Renders the users details
    """

    user = get_object_or_404(User, id=request.user.id)
    bookings = user.booker.all().order_by('-created_on')
    detail = user.details.first()
    
    if detail:
        fname = detail.first_name
        lname = detail.last_name
    else:
        fname = "FirstName"
        lname = "LastName"

    return render(
        request,
        "diary/diary.html",
        {
            "user": user,
            "bookings": bookings,
            "fname": fname,
            "lname": lname,
        },
    )

def booking_edit(request, slug, booking_id):
    """
    view to edit booking
    """

    if request.method == "POST":

        queryset = Movie.objects.all()
        movie = get_object_or_404(queryset, slug=slug)
        booking = get_object_or_404(Booking, pk=booking_id)
        user_booking = UserBooking(data=request.POST, instance=booking)

        if user_booking.is_valid() and booking.which_user == request.user:
            booking = user_booking.save(commit=False)
            booking.which_movie = movie
            booking.save()
            messages.add_message(request, messages.SUCCESS, 'Booking Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating booking!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))

home/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Movie
from .book_form import UserBooking
from diary.models import Booking
from django.contrib.auth.models import User


# Create your views here.

class MovieList(generic.ListView):
    queryset = Movie.objects.all()
    template_name = "home/index.html"
    #paginate_by = 6

def movie_detail(request, slug):
    """
    Display and individual :model:`home.Movie`.

    **Context**

    ``movie``
        An instance of :model:`home.Movie`.

    **Template**

    :template:`blog/movie_detail.html`
    """

    queryset = Movie.objects.all()
    movie = get_object_or_404(queryset, slug=slug)
    image_index = "/static/images/"+ movie.movie_image +".jpg"

    if request.method == "POST":
        user_booking = UserBooking(data=request.POST)
        if user_booking.is_valid():
            booking = user_booking.save(commit=False)
            booking.which_user = request.user
            booking.which_movie = movie
            booking.save()
            messages.add_message(
                request, messages.SUCCESS,
                'You have successfully made a booking!'
            )
    else:
        user_booking = UserBooking()
    return render(
        request,
        "home/movie_detail.html",
        {
            "movie": movie,
            "image_index": image_index,
            "user_booking": user_booking,
        },
    )

def booking_edit(request, slug, booking_id):
    """
    view to edit booking
    """

    if request.method == "POST":

        queryset = Movie.objects.all()
        movie = get_object_or_404(queryset, slug=slug)
        booking = get_object_or_404(Booking, pk=booking_id)
        user_booking = UserBooking(data=request.POST, instance=booking)

        if user_booking.is_valid() and booking.which_user == request.user:
            booking = user_booking.save(commit=False)
            booking.which_movie = movie
            booking.save()
            messages.add_message(request, messages.SUCCESS, 'Booking Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating booking!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))

diary/templates/diary/diary.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container mt-5">
  <div class="row">
    <div class="col-8">
      <!-- Title goes between these h2 tags -->
       {% if user.is_authenticated %}
      <h2>Username: {{ user }}</h2>
      {% else %}
      <p class="text-end m-3">Not logged in</p>
      {% endif %}
      <!-- Content goes directly underneath this -->
      <p>{{ fname }} {{lname}}</p>
      
      <hr/>
      <p>Email address: {{ user.email }}</p>
      <hr/>
    </div>
  </div>
  <div class="row">
    <h2>Bookings</h2>
    <hr/>
    {% for booking in bookings %}
    <h2>Movie: {{booking.which_movie.movie_title}}</h2>
    <p>{{booking.which_movie.meal_name}}</p>
    <p>Booked for: {{booking.get_which_day_display}}</p>
    <p>Booking created at: {{booking.created_on}}</p>
    <hr/>
    {% if user.is_authenticated and booking.which_user == user %}
    <script>
      const slug = "{{booking.which_movie.slug}}";
    </script>
    <button class="btn btn-edit"
    booking_id="{{ booking.id }}" movie_id="{{ booking.which_movie }}">Edit</button>
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/bookings.js' %}"></script>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for movie in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <a href="{% url 'movie_detail' movie.slug %}" class="movie-link">
                                <h2 class="movie-title">{{ movie.movie_title }}</h2>
                            </a>

                            <hr />
                            <h5 class="movie-subtitle">{{ movie.movie_year }}</h5>
                            <!--<img src="{% static 'images/pp4-art-m1.jpg' %}"  width="250">-->
                            <!--
                            <hr />
                            <div class="image-container">
                                <div class="image-flash">
                                    <p class="card-text">{{ movie.movie_desc }}</p>
                                </div>
                            </div>
                            -->
                            <hr />
                            <h3 class="movie-subtitle">{{ movie.meal_name}}
                            </h3>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

home/templates/home/movie_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Movie title goes in these h1 tags -->
                <h1 class="movie-title">{{ movie.movie_title }}</h1>
                <!--Movie year and director goes here-->
                <h3 class="movie-subtitle">{{ movie.movie_year }}</h3>
                <!-- Meal name goes below the movie name-->
                <h2 class="movie-subtitle">{{ movie.meal_name }}</h2>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <img src="{{image_index}}" class="scale" alt="placeholder">
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The movie description goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text">
                    {{ movie.movie_desc | safe }}
                </p>
            </div>
        </div>
    </div>
</div>
<!--Making a booking-->
<div class="col-md-12 card mb-4 mt-3">
    <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Make a booking:</h3>
        <form id="userBooking" method="post"
        style="margin-top: 1.3em;">
        {{ user_booking | crispy }}
        {% csrf_token %}
        <button id="submitButton" type="submit"
         class="btn btn-signup btn-lg">Book!</button>
        </form>
        {% else %}
        <p>Log in to make a booking!</p>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'diary' as diary_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Classics and Cuisine</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom CSS -->
     <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand"><span class="red-o">C</span>lassics</span><span
                class="thin"> and </span><span class="brand"><span class="red-o">C</span>uisine</span></span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page"
                            href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a
                        class="nav-link
                        {% if request.path == diary_url %}active{%endif%}"
                        aria-current="page"
                        href="{% url 'diary' %}"
                        >Profile</a
                        >
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page" href="{% url 'account_signup' %}">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    {% if user.is_authenticated %}
                    <p class="text-end m-3">You are logged in as {{ user }}</p>
                    {% else %}
                    <p class="text-end m-3">You are not logged in</p>
                    {% endif %}
                </span>
            </div>
        </div>
    </nav>
    <!-- displaying Django messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible
            fade show" id="msg" role="alert">
            {{ message | safe }}
            <button type="button" class="btn-close"
            data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
             </div>
        </div>
    </div>
    <main class="flex-shrink-0 main-bg">

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">-Booking Website-</p>
        <p class="m-0 text-center text-white">Social Media: 
            <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i>
        </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    {% block extras %}
    <script src="{% static 'js/comments.js' %}"></script>
    {% endblock %}
</body>

</html>